### ISSUE TITLE
Statistics map labels do not fit in boxes for RTL languages

### ISSUE THREAD

**Issue by q30a** [yanivam/react-path-tooltip#47]
**Describe the bug**
Statistics map labels do not fit in boxes for RTL languages

**To Reproduce** Steps to reproduce the behavior:
1. Go to [Flathub beta](https://beta.flathub.org/ar/statistics) - this is RTL language version of statistics map.
2. Hover over countries.
4. See error: labels do not fit in the boxes.

**Expected behavior**
Labels always fit in the boxes regardless of language selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/105132988/168472340-7d490a1b-97d9-469b-bcfe-28c06b722388.png)

**Desktop (please complete the following information):**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0

**Comment by razzeee** [comment]
@yanivam mind taking a look at this now :)

**Comment by yanivam** [comment]
Hey @razzeee, this is on my to do list as well don't worry. My queue right now is the vite issue here https://github.com/yanivam/react-svg-worldmap/issues/134, making it clear where I am getting the data from which is multiple issues and this. I am hoping to get it all done this weekend. Thanks for bearing with me!

**Comment by yanivam** [comment]
@razzeee and @q30a I believe this is fixed. If you pass the parameter "rtl" the value of true, you should be able to see text that is right to left. Let me know if this works. Thanks, Yams

**Comment by razzeee** [comment]
It doesn't seem to work as far as I can tell, did I miss anything?

 https://github.com/flathub/website/pull/1316

**Comment by yanivam** [comment]
Hey @razzeee, hmmm, did you write it like this: 
`import * as React from "react";
import type { CountryContext } from "react-svg-worldmap";
import WorldMap from "react-svg-worldmap";
import { populationData } from "../data/CountryData";

// Spanish translation of country names
const localizedCountryDictionary = new Map<string, string>([
  ["br", "البرازيل"], // Brazil
  ["cn", "الصين"], // China
  ["id", "إندونيسيا"], // Indonesia
  ["in", "الهند"], // India
  ["mx", "المكسيك"], // Mexico
  ["ng", "نيجيريا"], // Nigeria
  ["ru", "روسيا"], // Russia
  ["us", "الولايات المتحدة"], // United States
]);

// Spanish number formatting for thousands, millions, and billions
// E.g. translate the number 1000000 to "1 millónes"
function localizeNumber(num: number | undefined, digits: number) {
  if (typeof num === "undefined") return "";
  const magnitude = [
    { value: 1e9, text: " مليار " },
    { value: 1e6, text: " مليون " },
    { value: 1e3, text: " ألف " },
    { value: 1, text: "" },
  ].find((magnitude) => num >= magnitude.value);
  if (magnitude) {
    return (
      (num / magnitude.value)
        .toFixed(digits)
        .replace(/\.0+$|(?<number>\.[0-9]*[1-9])0+$/, "$1") + magnitude.text
    );
  }
  return "";
}

const getLocalizedText = ({
  countryCode,
  countryValue,
  prefix,
  suffix,
}: CountryContext) =>
  `${
    localizedCountryDictionary.get(countryCode.toLocaleLowerCase()) ?? "Unknown"
  }: ${prefix}${localizeNumber(countryValue, 2)}${suffix}`;

export default function App(): JSX.Element {
  return (
    <WorldMap
      title="الدول العشر الأولى من حيث عدد السكان"
      data={populationData}
      valueSuffix="الناس"
      tooltipTextFunction={getLocalizedText}
    />
  );
}
`
<img width="675" alt="Screenshot 2023-04-02 at 8 48 30 PM" src="https://user-images.githubusercontent.com/19212091/229388925-c88e3dfe-bea8-4971-89e9-7f99fb9c76a7.png">

**Comment by razzeee** [comment]
I'm not sure what's the difference, if I use your example problem with my data, the problem still shows.

**Comment by yanivam** [comment]
@razzeee Without being able to replicate the issue it is hard for me to tell what is causing it. Can you try to just use my example and see if it works first? Or can you try to reproduce the error on a small subset of your data and include that data in this thread? Without being able to reproduce it it is hard to diagnose the issue on my end.

**Comment by razzeee** [comment]
I'm using this code, to set the html tag to be RTL 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir

Setting this seems to cause the problem here

```
  useEffect(() => {
    document.dir = i18n.dir()
  }, [i18n, i18n.language])
```

**Comment by yanivam** [comment]
Interesting, I am not familiar with i18n. Is the line
```
rtl={i18n.dir() === "rtl"}
```
causing the issue? Make sure that it is returning "true" properly when expected.

**Comment by razzeee** [comment]
No, even if I put `{true}` into it it breaks the same way. It's probably due to the page being rendered rtl and probably your styling not respecting that correctly?

**Comment by yanivam** [comment]
I can't really be certain unless I can reproduce the issue. Can you provide a subset of your data like what I wrote above? In the form of the following:
```
const localizedCountryDictionary = new Map<string, string>([
  ["br", "البرازيل"], // Brazil
  ["cn", "الصين"], // China
  ["id", "إندونيسيا"], // Indonesia
  ["in", "الهند"], // India
  ["mx", "المكسيك"], // Mexico
  ["ng", "نيجيريا"], // Nigeria
  ["ru", "روسيا"], // Russia
  ["us", "الولايات المتحدة"], // United States
]);
```
If the problem is with the interaction between data and style then it will be helpful to understand what data + style combo is causing the issue. No matter what I do, I can't seem to get the same thing happening and so it is very hard for me to debug on my end without seeing it happen first.

**Comment by razzeee** [comment]
You can go to https://yanivam.github.io/react-svg-worldmap/examples/sizing and just change dir in the html tag to `rtl` and it will break.

![image](https://user-images.githubusercontent.com/5943908/229924234-a2ac4376-af79-4fee-9b4f-40406af79eaa.png)

**Comment by yanivam** [comment]
@razzeee hey, I think the issue is I forgot to run my build. Can you try it now with the latest map version?

**Comment by razzeee** [comment]
Perfect, seems to be working now

**Comment by yanivam** [comment]
Awesome! Closing the issue
